# netlify config for pythonpirates redirect
[build]
  publish = "site"
  command = ""

[[redirects]]
  from = "/*"
  to = "https://www.pythonpyrates.org/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.pythonpirates.org/*"
  to = "https://www.pythonpyrates.org/"
  status = 302
  force = true
